# Generated by Django 5.1.6 on 2025-03-10 10:27

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва роботи')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField(blank=True, verbose_name='Опис роботи')),
                ('type_of_work', models.IntegerField(choices=[(0, 'Онлайн-репетитор'), (1, 'Контрольна'), (2, "Розв'язання задач"), (3, 'Курсова'), (4, 'Реферат'), (5, 'Онлайн-допомога'), (6, 'Тест дистанційно'), (7, 'Диплом'), (8, 'Лабораторна'), (9, 'Креслення'), (10, 'Звіт з практики'), (11, 'Есе'), (12, 'Відповіді на квитки'), (13, 'Презентація'), (14, 'Переклад з ін. мови'), (15, 'Доповідь'), (16, 'Стаття'), (17, 'Твір'), (18, 'Магістерська дисертація'), (19, 'Кандидатська дисертація'), (20, 'Бізнес-план'), (21, 'Підбір літератури'), (22, 'Шпаргалка'), (23, 'Пошук інформації'), (24, 'Без статусу')], default=24, verbose_name='Тип роботи')),
                ('subject', models.CharField(max_length=255, verbose_name='Предмет')),
                ('plagiarism_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Рівень унікальності (%)', max_digits=5, verbose_name='Антиплагіат')),
                ('order_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Сума замовлення в грн', max_digits=10, verbose_name='Сума')),
                ('file_upload', models.FileField(blank=True, help_text='Додайте файл (якщо потрібно)', null=True, upload_to='order_files/', verbose_name='Файл')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('deadline', models.DateTimeField(default=orders.models.Order.default_deadline, verbose_name='Термін здачі замовлення')),
                ('status', models.IntegerField(choices=[(0, 'Без виконавця'), (1, 'В роботі'), (2, 'Замовлення виконане')], default=0, verbose_name='Статус')),
                ('customer', models.ForeignKey(blank=True, default=orders.models.get_default_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL, verbose_name='Замовник')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executor_orders', to=settings.AUTH_USER_MODEL, verbose_name='Виконавець')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-time_create'],
            },
        ),
    ]
