# Generated by Django 5.1.6 on 2025-03-19 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL, verbose_name='Замовник'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_of_work',
            field=models.IntegerField(choices=[(0, 'Онлайн-репетитор'), (1, 'Контрольна'), (2, "Розв'язання задач"), (3, 'Курсова'), (4, 'Реферат'), (5, 'Онлайн-допомога'), (6, 'Тест дистанційно'), (7, 'Диплом'), (8, 'Лабораторна'), (9, 'Креслення'), (10, 'Звіт з практики'), (11, 'Есе'), (12, 'Відповіді на квитки'), (13, 'Презентація'), (14, 'Переклад з ін. мови'), (15, 'Доповідь'), (16, 'Стаття'), (17, 'Твір'), (18, 'Магістерська дисертація'), (19, 'Кандидатська дисертація'), (20, 'Бізнес-план'), (21, 'Підбір літератури'), (22, 'Шпаргалка'), (23, 'Пошук інформації'), (24, 'Без предмету')], default=24, verbose_name='Тип роботи'),
        ),
    ]
