# Generated by Django 5.1.6 on 2025-05-29 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_set', to='orders.order', verbose_name='Замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Без виконавця'), (1, 'В роботі'), (2, 'Замовлення виконане'), (3, 'Неактивне')], default=0, verbose_name='Статус'),
        ),
    ]
