# Generated by Django 5.1.6 on 2025-06-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_bid_order_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Коментар виконавця'),
        ),
    ]
