# Generated by Django 5.1.6 on 2025-06-23 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_bid_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='orders.order', verbose_name='Замовлення'),
        ),
    ]
